### ISSUE TITLE
Process enhancements

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/manticoresearch-buddy#244]
We need to improve several things in Buddy's process realizations:
* Add process starting from Handler
* Now at one time we run only one process. It's unacceptable for Kafka brokers, cause each broker connects to his own partition, and the coroutine approach leads us to Kafka's rebalancing. As a result, we got the same single working thread instead of the desired count of consumers
* Workers pool. We need to have the ability to stop the desired worker. To do this better to have some sort of process pool

**Comment by djklim87** [comment]
This issue is blocker for https://github.com/manticoresoftware/manticoresearch/issues/1500

**Comment by djklim87** [comment]
A couple words about Kafka threads (how to reproduce this easily)

1. Checkout at `feat/queues` branch
2. Run run buddy with and Kafka 
```
docker compose -f docker-compose-dev.yml up -d
```
3. Create topics
```
docker exec kafka /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic my-data --partitions 4 --bootstrap-server localhost:9092
docker exec kafka /opt/bitnami/kafka/bin/kafka-topics.sh --describe --topic my-data --bootstrap-server localhost:9092
```
3. Run searchd 
```
docker exec manticore-buddy searchd
```
4. Run queries that should pass settings for workers:
```
docker exec manticore-buddy mysql -h0 -P9306 -e "CREATE SOURCE kafka (id bigint, term text, abbrev text, GlossDef json) type='kafka' broker_list='kafka:9092' topic_list='my-data' consumer_group='manticore' num_consumers='4' batch=50; CREATE TABLE destination_kafka (id bigint, name text, short_name text, received_at text, size multi); CREATE MATERIALIZED VIEW view_table TO destination_kafka AS SELECT id, term as name, abbrev as short_name, UTC_TIMESTAMP() as received_at, GlossDef.size as size FROM kafka"
```
5. Restart searchd (cause we processes now runs only on buddy start)
```
docker exec manticore-buddy searchd --stop
docker exec manticore-buddy searchd --nodetach
```


As result we see in logs records:
```
[BUDDY] ------->> Start worker kafka_1 
[BUDDY] ------->> .... kafka_1 
[BUDDY] ------->> Start worker kafka_2 
[BUDDY] ------->> .... kafka_2 
[BUDDY] ------->> Start worker kafka_3 
[BUDDY] ------->> .... kafka_3 
[BUDDY] ------->> Start worker kafka_0 
[BUDDY] ------->> .... kafka_0 
```
That's means that 4 workers were ~started~ sent to Swoole. But below we also see only one record about `run()` method call, instead 4 expected
```
[BUDDY] ------->> Start consuming kafka_2 
```

**Comment by donhardman** [comment]
I've added the Workers logic to buddy-core and updated the code for it to work in the `feat/queues` branch. Please review the comments, and don't hesitate to ask if anything else is needed to make it happen.

For executing it from the Handler, please use the "processor->execute" method. This will not only send the message to start a new worker but also add it to the pool.

![Image](https://github.com/manticoresoftware/manticoresearch-buddy/assets/59067742/97a834e1-9d36-4f64-baf7-b7ec8b2cb57b)

Please review and fill free to merge: https://github.com/manticoresoftware/buddy-core/pull/36

**Comment by djklim87** [comment]
Worker stop or any similar actions not stop workers

**Comment by donhardman** [comment]
I have pushed modifications to `features/workers` and `feat/queues`. Please let me know if it helped or not

**Comment by djklim87** [comment]
No it's still not working as it should.

I see in logs worker termination call
```
[BUDDY] [process] execute: stopWorkerById ["kafka_0"] 
[BUDDY] [1877µs] manticore request: query=DELETE+FROM+_views+WHERE+id+%3D+8937746421029797890 
[BUDDY] [process] execute: stopWorkerById ["kafka_1"] 
```
But later in the same log I see worker's activity
```
[BUDDY] -----> KafkaWorker worker -> Assign: [{},{}] 
last message repeated 1 times
[BUDDY] Sharding Event: ping [] 
[BUDDY] [1889µs] manticore request: query=SHOW+TABLES+LIKE+%27sharding_state%27 
[BUDDY] Node ID: 127.0.0.1:9312 
[BUDDY] Sharded: no 
[BUDDY] [1263µs] manticore request: query=SHOW+TABLES+LIKE+%27sharding_state%27 
[BUDDY] -----> KafkaWorker worker -> No more messages; will wait for more
